### ISSUE TITLE
Epic: Gracie CD

### ISSUE THREAD

**Issue by dsotirakis** [grafana/grafana-ci-otel-collector#30]
This issue is used to track all the things Gracie CD work.

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/grafana-ci-otel-collector/issues/31
- [ ] https://github.com/grafana/grafana-ci-otel-collector/issues/32
- [ ] https://github.com/grafana/grafana-ci-otel-collector/issues/40
```
