### ISSUE TITLE
Epic: Move Gracie to `prod`

### ISSUE THREAD

**Issue by dsotirakis** [grafana/grafana-ci-otel-collector#69]
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/deployment_tools/issues/87905
- [x] Add secrets to prod
- [x] Make sure Gracie works on prod
```
